/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_omron_hvcw_VideoFrame */

#ifndef _Included_jp_co_omron_hvcw_VideoFrame
#define _Included_jp_co_omron_hvcw_VideoFrame
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
