/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_omron_hvcw_HvcwApi */

#ifndef _Included_jp_co_omron_hvcw_HvcwApi
#define _Included_jp_co_omron_hvcw_HvcwApi
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FALSE
#define jp_co_omron_hvcw_HvcwApi_HVCW_FALSE 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_TRUE
#define jp_co_omron_hvcw_HvcwApi_HVCW_TRUE 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionMode_Auto
#define jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionMode_Auto 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionMode_Manual
#define jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionMode_Manual 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionStatus_Off
#define jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionStatus_Off 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionStatus_On
#define jp_co_omron_hvcw_HvcwApi_HVCW_NightVisionStatus_On 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_ConnectionNum
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_ConnectionNum 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_StreamingNum
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_StreamingNum 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_NightVisionMode
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_NightVisionMode 6L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_NightVisionStatus
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_NightVisionStatus 7L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_SpeakerVolume
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_SpeakerVolume 9L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_Disconnected
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_Disconnected 13L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_Reconnected
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_Reconnected 14L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Event_StorageStatus
#define jp_co_omron_hvcw_HvcwApi_HVCW_Event_StorageStatus 18L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotInsert
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotInsert 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotReady
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotReady 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NeedFormat
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NeedFormat 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Normal
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Normal 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Error
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Error 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Formatting
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_Formatting 6L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotSupport
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageStatus_NotSupport 7L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_Success
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_Success 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_RemovedStorage
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_RemovedStorage 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_NotSupportStorage
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_NotSupportStorage 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_Timeout
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_Timeout 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_AlreadyRunning
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_AlreadyRunning 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_CheckDisk
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_CheckDisk 5L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_FatalError
#define jp_co_omron_hvcw_HvcwApi_HVCW_StorageFormatResultCode_FatalError 6L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Disconnect
#define jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Disconnect 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_P2P
#define jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_P2P 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Relay
#define jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Relay 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Local
#define jp_co_omron_hvcw_HvcwApi_HVCW_ConnectionType_Local 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_High
#define jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_High 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_Middle
#define jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_Middle 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_Low
#define jp_co_omron_hvcw_HvcwApi_HVCW_VideoResolution_Low 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_Log
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_Log 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_MessageText
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_MessageText 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_Sound
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_Sound 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_JpgImage
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_JpgImage 6L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_YUVImage
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_YUVImage 7L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_ThumbnailJpgImage
#define jp_co_omron_hvcw_HvcwApi_HVCW_FileExt_ThumbnailJpgImage 8L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_OneTime
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_OneTime 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_Repeat
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_Repeat 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleType_Max 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Sound
#define jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Sound 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Motion
#define jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Motion 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Timer
#define jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Timer 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_EventProgramType_Max 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_FullHD
#define jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_FullHD 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_HD
#define jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_HD 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_WVGA
#define jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_WVGA 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_WQVGA
#define jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_WQVGA 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_ImageSize_Max 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Once
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Once 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Daily
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Daily 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Weekday
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Weekday 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_ScheduleFrequency_Max 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_None
#define jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_None 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_All
#define jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_All 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_Detection
#define jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_Detection 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_SaveResult_Max 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_None
#define jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_None 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_All
#define jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_All 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Known
#define jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Known 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Unknown
#define jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Unknown 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_FRSaveResult_Max 4L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_0
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_0 4097L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_1
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_1 8194L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_2
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_2 16388L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_3
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_3 32776L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_4
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_4 65552L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_5
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_5 131104L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_6
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_6 262208L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_7
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_7 524416L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_8
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_8 1048832L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_9
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_9 2097664L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_10
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_10 4195328L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_11
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_11 8390656L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_ALL
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_ALL 16777215L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_NONE
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_NONE 0L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_U15
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_U15 4097L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_R15
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_R15 32776L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_D15
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_D15 262208L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_L15
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_L15 2097664L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_UP
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_UP 4097L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_RIGHT
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_RIGHT 32776L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_DOWN
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_DOWN 262208L
#undef jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_LEFT
#define jp_co_omron_hvcw_HvcwApi_ROLL_ANGLE_LEFT 2097664L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Body
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Body 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Hand
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Hand 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Pet
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Pet 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Face
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Face 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Direction
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Direction 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Age
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Age 5L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Gender
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Gender 6L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Gaze
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Gaze 7L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Blink
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Blink 8L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Expression
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Expression 9L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Recognition
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Recognition 10L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_OkaoFunction_Max 11L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Ignore
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Ignore -1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Neutral
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Neutral 0L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Happiness
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Happiness 1L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Anger
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Anger 2L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Surprise
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Surprise 3L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Sadness
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Sadness 4L
#undef jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Max
#define jp_co_omron_hvcw_HvcwApi_HVCW_Expression_Max 5L
/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getVersion
 * Signature: (Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getVersion
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    createHandleNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_omron_hvcw_HvcwApi_createHandleNative
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    deleteHandle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_deleteHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setCameraHandle
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setCameraHandle
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    connect
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_connect
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    disconnect
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_disconnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getCameraVersion
 * Signature: (JLjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getCameraVersion
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    updateFirmware
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_updateFirmware
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setNightVisionMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setNightVisionMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getNightVisionMode
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getNightVisionMode
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setNightVisionStatus
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setNightVisionStatus
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getNightVisionStatus
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getNightVisionStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    enableEventMonitor
 * Signature: (JLjava/lang/Object;Ljp/co/omron/hvcw/EventCallbackInterface;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_enableEventMonitor
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    disableEventMonitor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_disableEventMonitor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setSpeakerVolume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setSpeakerVolume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getSpeakerVolume
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getSpeakerVolume
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setMicSensitivity
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setMicSensitivity
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getMicSensitivity
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getMicSensitivity
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getWiFiRSSI
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getWiFiRSSI
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    generateDataSoundFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_generateDataSoundFile
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    requestStorageFormat
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_requestStorageFormat
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getConnectionType
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getConnectionType
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    startLive
 * Signature: (JLjava/lang/Object;ILjp/co/omron/hvcw/RequestRenderingCallbackInterface;Ljp/co/omron/hvcw/LiveEventCallbackInterface;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_startLive
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    stopLive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_stopLive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    freeDecodedVideoBuffer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_freeDecodedVideoBuffer
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    freeDecodedAudioBuffer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_freeDecodedAudioBuffer
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    enterTalkMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_enterTalkMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    exitTalkMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_exitTalkMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    transferSoundData
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_transferSoundData
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setVideoResolution
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setVideoResolution
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getVideoResolution
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getVideoResolution
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    enableSoundDetection
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_enableSoundDetection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    disableSoundDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_disableSoundDetection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getSoundDetection
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getSoundDetection
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    enableMotionDetection
 * Signature: (JI[Ljp/co/omron/hvcw/DetectionParam;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_enableMotionDetection
  (JNIEnv *, jobject, jlong, jint, jobjectArray);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    disableMotionDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_disableMotionDetection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getMotionDetection
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;[Ljp/co/omron/hvcw/DetectionParam;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getMotionDetection
  (JNIEnv *, jobject, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getCameraMacAddress
 * Signature: (JLjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getCameraMacAddress
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    checkNewFirmware
 * Signature: (JLjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_checkNewFirmware
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getStorageInfo
 * Signature: (JLjp/co/omron/hvcw/StorageInfo;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getStorageInfo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getVideoFrame
 * Signature: (JLjp/co/omron/hvcw/VideoFrame;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getVideoFrame
  (JNIEnv *, jobject, jlong, jobject);
  
/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getSoundData
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getSoundData
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setAppID
 * Signature: (JILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setAppID
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getAppID
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getAppID
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setOkaoMode
 * Signature: (JILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setOkaoMode
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getOkaoMode
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getOkaoMode
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getFileCount
 * Signature: (JILjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getFileCount
  (JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getFileInfo
 * Signature: (JIILjp/co/omron/hvcw/FileInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getFileInfo
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    downloadFile
 * Signature: (JLjp/co/omron/hvcw/FileInfo;[BLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_downloadFile
  (JNIEnv *, jobject, jlong, jobject, jbyteArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    uploadFile
 * Signature: (JLjava/lang/String;I[BLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_uploadFile
  (JNIEnv *, jobject, jlong, jstring, jint, jbyteArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    deleteFile
 * Signature: (JLjp/co/omron/hvcw/FileInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_deleteFile
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getLastOkaoImageSize
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getLastOkaoImageSize
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getLastOkaoImage
 * Signature: (JI[BLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getLastOkaoImage
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    takePicture
 * Signature: (JLjp/co/omron/hvcw/FileInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_takePicture
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setThreshold
 * Signature: (JIIIIILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setThreshold
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getThreshold
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getThreshold
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setSizeRange
 * Signature: (JIIIIIIIILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setSizeRange
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getSizeRange
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getSizeRange
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setDetectionAngle
 * Signature: (JIIIIILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setDetectionAngle
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getDetectionAngle
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getDetectionAngle
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    okaoExecute
 * Signature: (J[ILjp/co/omron/hvcw/OkaoResult;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_okaoExecute
  (JNIEnv *, jobject, jlong, jintArray, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumRegister
 * Signature: (JIILjp/co/omron/hvcw/ResultDetection;Ljp/co/omron/hvcw/FileInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumRegister
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumSetUserName
 * Signature: (JILjava/lang/String;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumSetUserName
  (JNIEnv *, jobject, jlong, jint, jstring, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumGetUserName
 * Signature: (JILjava/lang/StringBuffer;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumGetUserName
  (JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumDeleteData
 * Signature: (JIILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumDeleteData
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumDeleteAllData
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumDeleteAllData
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumGetRegistrationStatus
 * Signature: (JI[ILjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumGetRegistrationStatus
  (JNIEnv *, jobject, jlong, jint, jintArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumGetSize
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumGetSize
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumDownload
 * Signature: (J[BLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumDownload
  (JNIEnv *, jobject, jlong, jbyteArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumUpload
 * Signature: (JI[BLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumUpload
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    albumSave
 * Signature: (JLjp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_albumSave
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setScheduler
 * Signature: (JIILjp/co/omron/hvcw/ScheduleInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setScheduler
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getScheduler
 * Signature: (JILjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/ScheduleInfo;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getScheduler
  (JNIEnv *, jobject, jlong, jint, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setSoundEventProgram
 * Signature: (JILjp/co/omron/hvcw/EventProgramSound;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setSoundEventProgram
  (JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setMotionEventProgram
 * Signature: (JIILjp/co/omron/hvcw/EventProgramMotion;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setMotionEventProgram
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    setTimerEventProgram
 * Signature: (JILjp/co/omron/hvcw/EventProgramTimer;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_setTimerEventProgram
  (JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getSoundEventProgram
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/EventProgramSound;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getSoundEventProgram
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getMotionEventProgram
 * Signature: (JLjp/co/omron/hvcw/Int;ILjp/co/omron/hvcw/EventProgramMotion;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getMotionEventProgram
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jobject);

/*
 * Class:     jp_co_omron_hvcw_HvcwApi
 * Method:    getTimerEventProgram
 * Signature: (JLjp/co/omron/hvcw/Int;Ljp/co/omron/hvcw/EventProgramTimer;Ljp/co/omron/hvcw/Int;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_omron_hvcw_HvcwApi_getTimerEventProgram
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
