jar cf ..\..\bin\jar\HVCW.jar^
 jp\co\omron\hvcw\DetectionParam.class^
 jp\co\omron\hvcw\EpAge.class^
 jp\co\omron\hvcw\EpBody.class^
 jp\co\omron\hvcw\EpExpression.class^
 jp\co\omron\hvcw\EpFace.class^
 jp\co\omron\hvcw\EpFrNotification.class^
 jp\co\omron\hvcw\EpFrPostProcess.class^
 jp\co\omron\hvcw\EpFrPushAlert.class^
 jp\co\omron\hvcw\EpFrSound.class^
 jp\co\omron\hvcw\EpGender.class^
 jp\co\omron\hvcw\EpKnownuser.class^
 jp\co\omron\hvcw\EpMotionEvent.class^
 jp\co\omron\hvcw\EpNotification.class^
 jp\co\omron\hvcw\EpOkaoProcess.class^
 jp\co\omron\hvcw\EpPet.class^
 jp\co\omron\hvcw\EpPostProcess.class^
 jp\co\omron\hvcw\EpPushAlert.class^
 jp\co\omron\hvcw\EpRecognition.class^
 jp\co\omron\hvcw\EpSound.class^
 jp\co\omron\hvcw\EpSoundEvent.class^
 jp\co\omron\hvcw\EpTimerEvent.class^
 jp\co\omron\hvcw\ErrorCodes.class^
 jp\co\omron\hvcw\EventCallbackInterface.class^
 jp\co\omron\hvcw\EventProgramMotion.class^
 jp\co\omron\hvcw\EventProgramSound.class^
 jp\co\omron\hvcw\EventProgramTimer.class^
 jp\co\omron\hvcw\FileInfo.class^
 jp\co\omron\hvcw\HvcwApi.class^
 jp\co\omron\hvcw\Int.class^
 jp\co\omron\hvcw\LiveEventCallbackInterface.class^
 jp\co\omron\hvcw\OkaoResult.class^
 jp\co\omron\hvcw\Point.class^
 jp\co\omron\hvcw\Range.class^
 jp\co\omron\hvcw\Rect.class^
 jp\co\omron\hvcw\RequestRenderingCallbackInterface.class^
 jp\co\omron\hvcw\ResultAeg.class^
 jp\co\omron\hvcw\ResultBlink.class^
 jp\co\omron\hvcw\ResultBodys.class^
 jp\co\omron\hvcw\ResultDetection.class^
 jp\co\omron\hvcw\ResultDirection.class^
 jp\co\omron\hvcw\ResultExpression.class^
 jp\co\omron\hvcw\ResultFace.class^
 jp\co\omron\hvcw\ResultFaces.class^
 jp\co\omron\hvcw\ResultGaze.class^
 jp\co\omron\hvcw\ResultGender.class^
 jp\co\omron\hvcw\ResultHands.class^
 jp\co\omron\hvcw\ResultPet.class^
 jp\co\omron\hvcw\ResultPets.class^
 jp\co\omron\hvcw\ResultRecognition.class^
 jp\co\omron\hvcw\ScheduleInfo.class^
 jp\co\omron\hvcw\ScheduleTime.class^
 jp\co\omron\hvcw\StorageInfo.class
pause
