javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.DetectionParam
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpAge
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpBody
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpExpression
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpFace
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpFrNotification
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpFrPostProcess
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpFrPushAlert
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpFrSound
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpGender
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpKnownuser
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpMotionEvent
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpNotification
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpOkaoProcess
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpPet
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpPostProcess
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpPushAlert
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpRecognition
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpSound
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpSoundEvent
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EpTimerEvent
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ErrorCodes
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EventCallbackInterface
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EventProgramMotion
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EventProgramSound
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.EventProgramTimer
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.FileInfo
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.HvcwApi
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.Int
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.LiveEventCallbackInterface
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.OkaoResult
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.Point
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.Range
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.Rect
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.RequestRenderingCallbackInterface
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultAeg
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultBlink
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultBodys
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultDetection
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultDirection
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultExpression
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultFace
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultFaces
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultGaze
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultGender
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultHands
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultPet
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultPets
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ResultRecognition
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ScheduleInfo
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.ScheduleTime
javah -classpath . -d ..\HVCW_JNI -jni jp.co.omron.hvcw.StorageInfo

pause
